CC = gcc

CFLAGS = -Wall -Wextra -std=c11

TARGET = Permutation.exe

SRCS = main.c Permutation.c

OBJS = $(SRCS.c=.o)

all $(TARGET)

$(TARGET) $(OBJS)
	$(CC) $(CFLAGS) -o $(TARGET) $(OBJS)

%.o %.c
	$(CC) $(CFLAGS) -c $ -o $@

clean
	rm -f $(OBJS) $(TARGET)

run $(TARGET)
	.$(TARGET)